### ISSUE TITLE
Element with id "view_mode" already exists

### ISSUE THREAD

**Issue by timmeyy23** [webguys-de/EasyTemplate#33]
Hello,

if we want edit an CMS_Page we 've got this error:

Trace:
#0 /werqsowe/www.werkzeugstore24.de/lib/Varien/Data/Form/Element/Abstract.php(58): Varien_Data_Form->checkElementId('view_mode')
#1 /werqsowe/www.werkzeugstore24.de/lib/Varien/Data/Form/Abstract.php(148): Varien_Data_Form_Element_Abstract->addElement(Object(Varien_Data_Form_Element_Select), false)
#2 /werqsowe/www.werkzeugstore24.de/lib/Varien/Data/Form/Element/Fieldset.php(135): Varien_Data_Form_Abstract->addField('view_mode', 'select', Array, false)
#3 /werqsowe/www.werkzeugstore24.de/app/code/community/Webguys/Easytemplate/Model/Observer.php(37): Varien_Data_Form_Element_Fieldset->addField('view_mode', 'select', Array)
#4 /werqsowe/www.werkzeugstore24.de/app/code/core/Mage/Core/Model/App.php(1358): Webguys_Easytemplate_Model_Observer->adminhtml_cms_prepare_form(Object(Varien_Event_Observer))
#5 /werqsowe/www.werkzeugstore24.de/app/code/core/Mage/Core/Model/App.php(1337): Mage_Core_Model_App->_callObserverMethod(Object(Webguys_Easytemplate_Model_Observer), 'adminhtml_cms_p...', Object(Varien_Event_Observer))
#6 /werqsowe/www.werkzeugstore24.de/app/Mage.php(456): Mage_Core_Model_App->dispatchEvent('adminhtml_cms_p...', Array)
#7 /werqsowe/www.werkzeugstore24.de/app/code/core/Mage/Adminhtml/Block/Cms/Page/Edit/Tab/Main.php(119): Mage::dispatchEvent('adminhtml_cms_p...', Array)
#8 /werqsowe/www.werkzeugstore24.de/app/code/core/Mage/Adminhtml/Block/Widget/Form.php(144): Mage_Adminhtml_Block_Cms_Page_Edit_Tab_Main->_prepareForm()
#9 /werqsowe/www.werkzeugstore24.de/app/code/core/Mage/Core/Block/Abstract.php(918): Mage_Adminhtml_Block_Widget_Form->_beforeToHtml()
#10 /werqsowe/www.werkzeugstore24.de/app/code/core/Mage/Adminhtml/Block/Widget/Tabs.php(303): Mage_Core_Block_Abstract->toHtml()
#11 /werqsowe/www.werkzeugstore24.de/app/design/adminhtml/default/default/template/widget/tabs.phtml(38): Mage_Adminhtml_Block_Widget_Tabs->getTabContent(Object(Mage_Adminhtml_Block_Cms_Page_Edit_Tab_Main))
#12 /werqsowe/www.werkzeugstore24.de/app/code/core/Mage/Core/Block/Template.php(241): include('/werqsowe/www.w...')
#13 /werqsowe/www.werkzeugstore24.de/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#14 /werqsowe/www.werkzeugstore24.de/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#15 /werqsowe/www.werkzeugstore24.de/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#16 /werqsowe/www.werkzeugstore24.de/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Adminhtml_Block_Template->_toHtml()
#17 /werqsowe/www.werkzeugstore24.de/app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract->toHtml()
#18 /werqsowe/www.werkzeugstore24.de/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Text_List->_toHtml()
#19 /werqsowe/www.werkzeugstore24.de/app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#20 /werqsowe/www.werkzeugstore24.de/app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('left', true)
#21 /werqsowe/www.werkzeugstore24.de/app/design/adminhtml/default/default/template/page.phtml(58): Mage_Core_Block_Abstract->getChildHtml('left')
#22 /werqsowe/www.werkzeugstore24.de/app/code/core/Mage/Core/Block/Template.php(241): include('/werqsowe/www.w...')
#23 /werqsowe/www.werkzeugstore24.de/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#24 /werqsowe/www.werkzeugstore24.de/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#25 /werqsowe/www.werkzeugstore24.de/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#26 /werqsowe/www.werkzeugstore24.de/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Adminhtml_Block_Template->_toHtml()
#27 /werqsowe/www.werkzeugstore24.de/app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
#28 /werqsowe/www.werkzeugstore24.de/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
#29 /werqsowe/www.werkzeugstore24.de/app/code/core/Mage/Adminhtml/controllers/Cms/PageController.php(119): Mage_Core_Controller_Varien_Action->renderLayout()
#30 /werqsowe/www.werkzeugstore24.de/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_Cms_PageController->editAction()
#31 /werqsowe/www.werkzeugstore24.de/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('edit')
#32 /werqsowe/www.werkzeugstore24.de/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#33 /werqsowe/www.werkzeugstore24.de/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#34 /werqsowe/www.werkzeugstore24.de/app/Mage.php(692): Mage_Core_Model_App->run(Array)
#35 /werqsowe/www.werkzeugstore24.de/index.php(83): Mage::run('', 'store')
#36 {main}

Any suggests?

**Comment by tobi-pb** [comment]
Could you Quote your Version of magento and Easytemplate please?

**Comment by timmeyy23** [comment]
Hello , 

we use the Magento CE 1.9.2.4 and the Easytemplate Version 1.0.0.5

**Comment by timmeyy23** [comment]
Hello @tobi-pb  have you any news for me? 

Thank you!

**Comment by tobi-pb** [comment]
Hey timmey23,

sorry, we haven't got an 1.0.0.5 release yet. Just 0.9.0.\* stuff. 

https://github.com/webguys-de/EasyTemplate/releases

Could you quote your downloaded release number? Please use https://github.com/webguys-de/EasyTemplate/releases/tag/0.9.0.5

master is not stable at the moment :-(

**Comment by timmeyy23** [comment]
Hello,

thank you for your answer. 

I thought you mean the Version from the config.xml:   <modules>
        <Webguys_Easytemplate>
            <version>1.0.0.5</version>
        </Webguys_Easytemplate>
    </modules>

I downloaded the master, but thank you I will try your suggested version.

**Comment by tobi-pb** [comment]
Please re-open in case of having same problem, thanks

**Comment by timmeyy23** [comment]
Hello @tobi-pb, the suggested Version,  issue the same error. 
Maybe you have another idea? 

Thank you.
