### ISSUE TITLE
Element with id "view_mode" already exists

### ISSUE THREAD

**Issue by timmeyy23** [webguys-de/EasyTemplate#34]
Hello,

i can't reopen my issue. We have the same issue with the 0.9.0.5 release. 

Have you any idea how to fix this @tobi-pb ? 

Thank you in advance. 

Regards

**Comment by nrunde** [comment]
Same here with the 0.9.0.5 release :(
Is there a fix already?

**Comment by nrunde** [comment]
In our case an additional extension causes the error by adding a second fieldset to cms page configuration.
Little loop break in observer.php fixed the problem for me #36
