### ISSUE TITLE
Fehler bei three_products

### ISSUE THREAD

**Issue by Barto1983** [webguys-de/EasyTemplate#7]
Hallo,
erstmal vielen dank für das tolle Modul.

Folgender Fehler passiert bei mir wenn ich three_products einstelle:

Das Programm stürzt bei diesem Befehl ab:
app\design\frontend\xxx\default\template\catalog\product\price.phtml
$_specialPriceStoreLabel = $this->getProductAttribute('special_price')->getStoreLabel(); 

Mit freundlichen Grüßen

**Comment by tobi-pb** [comment]
Wir haben statt three_products nun die möglichkeit eine Produktliste einzufügen. D.h. einfach Artikelnummern nacheinander eingeben fertig :)
